### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by ainokuos** [vikke1234/ot-project#1]
## Koodikatselmointi
Projekti ladattu 3.5.2021 klo 20:00
### Yleistä
- Koodi on jaettu selkeästi hakemistoihin eri toiminnallisuuksien perusteella
        - Luokat toteuttavat vain yhtä toimintoa  
        - Metodit ja funktiot pysyvät yksinkertaisina
- Sovelluslogiikka on erillään käyttöliittymästä
- Pylintin antaman arvosanan mukaan koodin laatu on erittäin hyvää lukuunottamatta muutamaa muuttujaa 
### Huomioita
- src hakemistossa on vielä tiedostoja joita voisi jakaa erillisiin hakemistoihin, kuten olitkin jo maininnut arkkitehtuurikuvauksessa
- Hakemisto dialogs toistuu kahdesti ensin gui-hakemistossa ja myöhemmin myös gui/ui-hakemistossa, joka on jokseenkin hämäävää
        - Hakemistot sisältävät myös lähes samannimiset tiedostot

### Toiminnasta
En saanut ohjelmaa toimimaan fuksiläppärilläni. Yritin myös etätyöpöydällä ajaa viimeisimmän releasen koodia, mutta virheilmoituksena sain:
ModuleNotFoundError: No module named 'gui.models.saved_address_model'
Models hakemistosta on siis jäänyt ilmeisesti pois tuo moduuli.

Fuksiläppärillä ohjelma kyllä aukesi, mutta kaatui tiedoston valintaan, mikä taitaa johtua fuksiläppärin käyttöoikeuksien puutteesta. Tässä olisi voinut olla virheilmoitus ohjelman kaatumisen sijaan.

**Comment by vikke1234** [comment]
Joo siis olin unohtanu committaa ton filen ni sen takii ei toiminu. Ja syy miks siin on aika samoi tiedostoi siin `ui` folderis on kosk ne on vaa autogeneroitui ja ei mikään muu paitsi ne mitkä on siin gui kansios pitäs käyttää niit.
